-- 002_seed_materials.sql
-- Insere materiais seed para o admin

INSERT OR IGNORE INTO materials(id,nome,categoria,subcategoria,unidade,pegada_carbono,criado_em)
VALUES
('cimento_portland','Cimento Portland','estrutura','cimento','t',900,datetime('now')),
('concreto_usinado_misto','Concreto usinado (misto)','estrutura','concreto','m³',380,datetime('now')),
('aco_ca50_barras','Aço CA-50 (barras)','estrutura','aço','t',2500,datetime('now')),
('aco_estrutural_perfil','Aço estrutural (perfil I, H)','estrutura','aço','t',2750,datetime('now')),
('blocos_concreto','Blocos de concreto','alvenaria','bloco','milheiro',495,datetime('now')),
('tijolo_ceramico_comum','Tijolo cerâmico comum','alvenaria','tijolo','milheiro',495,datetime('now')),
('areia_media','Areia média (agregado)','agregados','areia','t',10,datetime('now')),
('brita_agregado','Brita (agregado)','agregados','brita','t',15,datetime('now')),
('pedra_rachao','Pedra rachão','agregados','pedra','t',15,datetime('now')),
('bloco_ceramico_estrutural','Bloco cerâmico estrutural','alvenaria','bloco','milheiro',525,datetime('now')),
('ceramica_revestimento','Cerâmica para revestimento','acabamento','revestimento','m²',20,datetime('now')),
('telha_ceramica_un','Telha cerâmica','cobertura','telha','un',4.5,datetime('now')),
('telha_fibrocimento','Telha fibrocimento','cobertura','telha','un',7,datetime('now')),
('madeira_serrada','Madeira serrada (estrutura)','estrutura','madeira','m³',245,datetime('now')),
('madeira_tratada','Madeira tratada','estrutura','madeira','m³',350,datetime('now')),
('painel_osb','Painel OSB','madeira','painel','m³',725,datetime('now')),
('painel_mdf','Painel de MDF','madeira','painel','m³',750,datetime('now')),
('tela_aco_armat','Tela de aço (armat)','estrutura','aço','t',2550,datetime('now')),
('ferro_fundido','Ferro fundido','estrutura','metal','t',2000,datetime('now')),
('tubos_pvc','Tubos PVC (água/esgoto)','hidraulica','tubos','m',4.5,datetime('now')),
('tubos_aco_galv','Tubos de aço galvanizado','hidraulica','tubos','m',20,datetime('now')),
('tinta_latex_pva','Tinta látex PVA','acabamento','tinta','L',1.0,datetime('now')),
('tinta_esmalte_sint','Tinta esmalte sintético','acabamento','tinta','L',1.8,datetime('now')),
('argamassa_acii','Argamassa (tipo AC-II)','acabamento','argamassa','saco',22,datetime('now')),
('rejunte_ceramico','Rejunte cerâmico','acabamento','rejunte','saco',4,datetime('now')),
('isolante_la_vidro','Isolante térmico (lã de vidro)','isolamento','lã','m²',2.8,datetime('now')),
('isolante_la_rocha','Isolante acústico (lã de rocha)','isolamento','lã','m²',3.5,datetime('now')),
('vidro_plano_temperado','Vidro plano (temperado)','acabamento','vidro','m²',20,datetime('now')),
('caixilhos_aluminio','Caixilhos de alumínio','esquadrias','caixilhos','m²',100,datetime('now')),
('caixilhos_aco','Caixilhos de aço','esquadrias','caixilhos','m²',140,datetime('now')),
('caixilhos_madeira','Caixilhos de madeira','esquadrias','caixilhos','m²',40,datetime('now')),
('parafusos_fixacao','Parafusos/metais de fixação','fixacao','metais','kg',10,datetime('now')),
('tubulacao_cobre','Tubulação de cobre (hidráulica)','hidraulica','tubos','kg',6,datetime('now')),
('cabos_eletricos','Cabos elétricos (cobre/isolante)','eletrica','cabos','kg',5,datetime('now')),
('interruptores_tomadas','Interruptores e tomadas','eletrica','acessorios','un',0.6,datetime('now')),
('luminarias_led','Luminárias (LED)','eletrica','iluminacao','un',4,datetime('now')),
('ceramica_pavers','Cerâmica técnica (pavers)','acabamento','pavers','m²',22,datetime('now')),
('placas_cimenticias','Placas cimentícias','vedacao','placas','m²',14,datetime('now')),
('placas_gesso_drywall','Placas de gesso (drywall)','vedacao','gesso','m²',8,datetime('now')),
('espuma_pu','Espuma PU (isolante)','isolamento','espuma','m³',200,datetime('now')),
('eps_poliestireno','Poliestireno expandido (EPS)','isolamento','poliestireno','m³',250,datetime('now')),
('betao_usinado_reforcado','Betão usinado reforçado','estrutura','concreto','m³',415,datetime('now')),
('placas_concreto_prefab','Placas de concreto pré-fabricadas','estrutura','concreto','m²',115,datetime('now')),
('lajes_prefabricadas','Lajes pré-fabricadas','estrutura','concreto','m²',100,datetime('now')),
('reboco_parede','Reboco de parede (argamassa)','acabamento','argamassa','m²',2.8,datetime('now')),
('piso_ceramico_esmaltado','Piso cerâmico esmaltado','acabamento','pisos','m²',22,datetime('now')),
('laminados_madeira','Laminados de madeira (pisos)','acabamento','pisos','m²',40,datetime('now')),
('porcelanato','Porcelanato','acabamento','pisos','m²',30,datetime('now')),
('tela_soldada','Tela soldada (armadura)','estrutura','aço','m²',18,datetime('now')),
('base_britada','Base britada para fundação','agregados','base','m³',20,datetime('now')),
('cascalho_agregado','Cascalho (agregado)','agregados','cascalho','m³',18,datetime('now')),
('formas_madeira','Formas de madeira','estrutura','madeira','m²',20,datetime('now')),
('alvenaria_estrutural_blocos','Alvenaria estrutural (blocos)','alvenaria','blocos','m³',375,datetime('now')),
('argamassa_colante','Argamassa colante (cerâmica)','acabamento','argamassa','saco',18,datetime('now')),
('silicone_selantes','Silicone/selantes','acabamento','selantes','tubo',1.2,datetime('now')),
('espuma_poliuretano_spray','Espuma de poliuretano (spray)','acabamento','espuma','lata',1.8,datetime('now')),
('revestimento_cimenticio','Revestimento cimentício decorativo','acabamento','revestimento','m²',14,datetime('now')),
('revestimento_vinilico','Revestimento vinílico (pisos)','acabamento','pisos','m²',18,datetime('now')),
('revestimento_laminado','Revestimento laminado','acabamento','pisos','m²',22,datetime('now')),
('revestimento_pvc','Revestimento plástico (PVC)','acabamento','revestimento','m²',12,datetime('now')),
('cimento_cp2','Cimento CP-II','estrutura','cimento','t',900,datetime('now')),
('cimento_cp3','Cimento CP-III','estrutura','cimento','t',820,datetime('now')),
('cal_hidratada','Cal hidratada','acabamento','cal','saco',8,datetime('now')),
('gesso_liso','Gesso liso (acabamento)','acabamento','gesso','saco',12,datetime('now')),
('tijolo_baiano','Tijolo baiano (furado)','alvenaria','tijolo','milheiro',480,datetime('now')),
('bloco_vedacao_concreto','Bloco de vedação concreto','alvenaria','bloco','milheiro',520,datetime('now')),
('argamassa_reboco','Argamassa para reboco','acabamento','argamassa','saco',20,datetime('now')),
('argamassa_assentamento','Argamassa para assentamento','acabamento','argamassa','saco',18,datetime('now')),
('massa_corrida_pva','Massa corrida PVA','acabamento','massa','saco',6,datetime('now')),
('massa_acrilica','Massa acrílica','acabamento','massa','saco',7,datetime('now')),
('verniz_madeira','Verniz para madeira','acabamento','verniz','L',1.2,datetime('now')),
('impermeabilizante_manta','Manta asfáltica','impermeabilizacao','manta','m²',12,datetime('now')),
('impermeabilizante_tinta','Impermeabilizante líquido','impermeabilizacao','tinta','L',2.5,datetime('now')),
('tubo_cpvc','Tubos CPVC','hidraulica','tubos','m',6,datetime('now')),
('tubo_ppr','Tubos PPR','hidraulica','tubos','m',5,datetime('now')),
('caixa_dagua_polietileno','Caixa d''água polietileno','hidraulica','reservatorio','un',40,datetime('now')),
('cimento_queimado','Cimento queimado (piso)','acabamento','piso','m²',8,datetime('now')),
('granito_revestimento','Granito (revestimento)','acabamento','revestimento','m²',35,datetime('now')),
('marmore_revestimento','Mármore (revestimento)','acabamento','revestimento','m²',40,datetime('now')),
('granilite_piso','Granilite (piso)','acabamento','piso','m²',18,datetime('now')),
('telha_termoacustica','Telha termoacústica','cobertura','telha','m²',12,datetime('now')),
('porta_madeira','Porta de madeira','esquadrias','porta','un',30,datetime('now')),
('janela_aluminio','Janela de alumínio','esquadrias','janela','un',45,datetime('now')),
('pisos_intertravados','Piso intertravado','acabamento','piso','m²',20,datetime('now')),
('cimento_colante_piso','Cimento colante (piso)','acabamento','argamassa','saco',16,datetime('now')),
('ferragem_estribos','Estribos (ferragem)','estrutura','aço','kg',2.5,datetime('now')),
('malha_pop','Malha POP','estrutura','aço','m²',12,datetime('now')),
('tubo_soldavel_pvc','Tubo soldável PVC','hidraulica','tubos','m',4.5,datetime('now')),
('caixa_eletrica','Caixa elétrica','eletrica','acessorios','un',0.2,datetime('now')),
('disjuntor','Disjuntor','eletrica','proteção','un',0.8,datetime('now')),
('conduite_corrugado','Conduíte corrugado','eletrica','eletroduto','m',0.6,datetime('now')),
('cimento_estrutural_premoldado','Concreto pré-moldado estrutural','estrutura','concreto','m³',400,datetime('now')),
('argamassa_autonivelante','Argamassa autonivelante','acabamento','argamassa','saco',22,datetime('now')),
('piso_vinilico_lvt','Piso vinílico (LVT)','acabamento','piso','m²',18,datetime('now'));
